(() => {
  const $ = s => document.querySelector(s);
  const api = (path, options={}) => fetch(path,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}).then(async r=>{const d=await r.json().catch(()=>({success:false,error:'پاسخ نامعتبر'}));if(r.status===401){location.href='/admin/login.html';throw new Error('احراز هویت لازم است.');}if(!r.ok||d.success===false)throw new Error(d.error||'خطای سرور');return d;});
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');
  const toast=(t,e=false)=>{let x=$('#monitoringToast');if(!x){x=document.createElement('div');x.id='monitoringToast';x.style.cssText='position:fixed;top:24px;right:24px;z-index:10002;max-width:min(460px,calc(100vw - 48px));padding:13px 18px;border-radius:12px;background:#fff;box-shadow:0 10px 30px rgba(0,0,0,.14);font-size:14px;font-weight:700';document.body.appendChild(x)}x.textContent=t;x.style.border=`1px solid ${e?'#fecaca':'#bbf7d0'}`;x.style.color=e?'#991b1b':'#166534';};
  const state={page:1,pageSize:10};
  async function load(page=state.page){state.page=page;const l=$('#leadsList');if(!l)return;l.innerHTML='<div class="leads-empty">در حال دریافت درخواست‌ها...</div>';try{const q=encodeURIComponent($('#leadSearch')?.value.trim()||''),s=encodeURIComponent($('#leadStatusFilter')?.value||''),d=await api(`/api/admin/leads?page=${page}&pageSize=${state.pageSize}&q=${q}&status=${s}`);renderStats(d.stats||{});render(d.leads||[]);paginate(d.pagination||{});}catch(e){l.innerHTML=`<div class="leads-empty">دریافت درخواست‌ها ناموفق بود: ${esc(e.message)}</div>`;}}
  function renderStats(s){const e=$('#leadStats');if(e)e.innerHTML=`<div class="lead-stat"><span>کل</span><strong>${Number(s.total||0)}</strong></div><div class="lead-stat"><span>جدید</span><strong>${Number(s.new_count||0)}</strong></div><div class="lead-stat"><span>در حال پیگیری</span><strong>${Number(s.in_progress_count||0)}</strong></div><div class="lead-stat"><span>انجام‌شده</span><strong>${Number(s.done_count||0)}</strong></div><div class="lead-stat"><span>ردشده</span><strong>${Number(s.rejected_count||0)}</strong></div>`;}
  function render(rows){const e=$('#leadsList');if(!rows.length){e.innerHTML='<div class="leads-empty">درخواستی برای نمایش وجود ندارد.</div>';return;}e.innerHTML=rows.map(l=>`<article class="lead-row"><div class="lead-main"><strong>${esc(l.full_name)}</strong><div class="lead-meta"><span>📞 ${esc(l.phone)}</span><span>${esc(l.brand||'بدون برند')}</span><span>${esc(l.type||'بدون نوع')}</span><span>${esc(l.created_at||'')}</span></div><div class="lead-description">${esc(l.description||'بدون توضیحات')}</div><div class="lead-details" id="leadDetails-${Number(l.id)}" hidden><div class="lead-details-grid"><div class="lead-field"><small>نام</small><div>${esc(l.full_name)}</div></div><div class="lead-field"><small>تلفن</small><div>${esc(l.phone)}</div></div><div class="lead-field"><small>برند</small><div>${esc(l.brand||'')}</div></div><div class="lead-field"><small>نوع نیاز</small><div>${esc(l.type||'')}</div></div><div class="lead-field"><small>منبع</small><div>${esc(l.source||'')}</div></div><div class="lead-field"><small>وضعیت پیامک مشتری / مدیر</small><div>${esc(l.customer_sms_status||'')} / ${esc(l.admin_sms_status||'')}</div></div></div><textarea class="lead-notes" data-notes="${Number(l.id)}" placeholder="یادداشت داخلی ادمین">${esc(l.admin_notes||'')}</textarea><button class="admin-button primary small lead-save-notes" data-id="${Number(l.id)}" type="button">ذخیره یادداشت</button></div></div><div class="lead-actions"><select class="lead-status lead-status-${esc(l.lead_status||'new')}" data-status="${Number(l.id)}"><option value="new" ${l.lead_status==='new'?'selected':''}>جدید</option><option value="in_progress" ${l.lead_status==='in_progress'?'selected':''}>در حال پیگیری</option><option value="done" ${l.lead_status==='done'?'selected':''}>انجام‌شده</option><option value="rejected" ${l.lead_status==='rejected'?'selected':''}>ردشده</option></select><button class="admin-button outline small lead-toggle" data-id="${Number(l.id)}" type="button">جزئیات</button></div></article>`).join('');e.querySelectorAll('.lead-toggle').forEach(b=>b.onclick=()=>{const d=$(`#leadDetails-${b.dataset.id}`);d.hidden=!d.hidden;b.textContent=d.hidden?'جزئیات':'بستن جزئیات';});e.querySelectorAll('.lead-status').forEach(s=>s.onchange=async()=>{try{await api(`/api/admin/leads/${Number(s.dataset.status)}`,{method:'POST',body:JSON.stringify({status:s.value})});toast('وضعیت درخواست ذخیره شد.');s.className=`lead-status lead-status-${esc(s.value)}`;}catch(e){toast(`ذخیره وضعیت ناموفق بود: ${e.message}`,true);load();}});e.querySelectorAll('.lead-save-notes').forEach(b=>b.onclick=async()=>{const id=Number(b.dataset.id),n=e.querySelector(`[data-notes="${id}"]`)?.value||'';b.disabled=true;try{await api(`/api/admin/leads/${id}`,{method:'POST',body:JSON.stringify({adminNotes:n})});toast('یادداشت ذخیره شد.');}catch(e){toast(`ذخیره یادداشت ناموفق بود: ${e.message}`,true);}finally{b.disabled=false;}});}
  function paginate(p){const e=$('#leadsPagination');if(!e)return;const t=Number(p.totalPages||1),c=Number(p.page||1);e.innerHTML=`<button ${c<=1?'disabled':''} data-page="${c-1}">قبلی</button>${Array.from({length:t},(_,i)=>`<button class="${i+1===c?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')}<button ${c>=t?'disabled':''} data-page="${c+1}">بعدی</button>`;e.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>load(Number(b.dataset.page)));}
  window.loadPayamakeLeads=load;
  function init(){
    if(location.pathname!=='/admin/'&&location.pathname!=='/admin/index.html')return;
    $('#refreshLeads')?.addEventListener('click',()=>load(1));
    $('#searchLeads')?.addEventListener('click',()=>load(1));
    $('#leadStatusFilter')?.addEventListener('change',()=>load(1));
    $('#leadSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();load(1);}});
    if(location.hash==='#leads')load(1);
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init,{once:true}); else init();
})();
