(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const api=async(path,o={})=>{const r=await fetch(path,{credentials:'include',...o,headers:{'Content-Type':'application/json',...(o.headers||{})}});const d=await r.json().catch(()=>({error:'پاسخ نامعتبر'}));if(!r.ok||d.success===false)throw Error(d.error||'خطای سرور');return d};
let modal,initialized=false;
function init(){
 if(initialized)return true;
 const actions=document.querySelector('.admin-header-actions');if(!actions)return false;
 initialized=true;
 let btn=document.getElementById('securityAccountButton');
 if(!btn){btn=document.createElement('button');btn.id='securityAccountButton';btn.type='button';btn.className='logout-button security-account-button';btn.title='حساب و امنیت';btn.setAttribute('aria-label','حساب و امنیت');btn.textContent='👤';actions.insertBefore(btn,actions.querySelector('#logoutButton'));}
 if(!document.getElementById('securityCenterStyles')){const s=document.createElement('style');s.id='securityCenterStyles';s.textContent='.security-account-button{width:42px;min-width:42px;padding:0;font-size:19px;display:inline-flex;align-items:center;justify-content:center}.security-modal{position:fixed;inset:0;z-index:99999;background:rgba(15,23,42,.48);display:none;align-items:center;justify-content:center;padding:18px}.security-modal.open{display:flex}.security-modal-card{width:min(1100px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 24px 80px rgba(15,23,42,.24);padding:22px;direction:rtl}.security-modal-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.security-modal-head h2{margin:0;font-size:20px}.security-modal-close{border:0;background:#f3f4f6;border-radius:9px;width:38px;height:38px;cursor:pointer;font-size:20px}.security-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.security-tabs button,.security-actions button{border:1px solid #ddd;background:#fff;border-radius:9px;padding:8px 11px;cursor:pointer;font:inherit}.security-tabs button.active{background:#111;color:#fff}.security-table{width:100%;border-collapse:collapse;font-size:13px}.security-table th,.security-table td{padding:9px;border-bottom:1px solid #eee;text-align:right;vertical-align:top}.security-actions{display:flex;gap:6px;flex-wrap:wrap}.security-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;margin-bottom:16px}.security-form input{padding:9px;border:1px solid #ddd;border-radius:8px;font:inherit}.security-form button{border:0;border-radius:8px;padding:9px 13px;background:#111;color:#fff;cursor:pointer;font:inherit}.security-note{padding:10px;background:#f7f7f7;border-radius:10px;margin-bottom:14px;font-size:13px}.security-empty{padding:18px;text-align:center;color:#667085}@media(max-width:700px){.security-modal{padding:8px}.security-modal-card{padding:15px;max-height:94vh}.security-table{font-size:12px;display:block;overflow:auto;white-space:nowrap}}';document.head.appendChild(s)}
 modal=document.createElement('div');modal.className='security-modal';modal.innerHTML='<div class="security-modal-card" role="dialog" aria-modal="true" aria-labelledby="securityModalTitle"><div class="security-modal-head"><h2 id="securityModalTitle">حساب و امنیت</h2><button type="button" class="security-modal-close" aria-label="بستن">×</button></div><div class="security-note">تنظیمات حساب مدیر، نشست‌ها، فعالیت ورود، IPهای مسدود و لاگ امنیتی در این بخش مدیریت می‌شود.</div><div class="security-tabs"><button data-tab="admins">مدیریت مدیران</button><button data-tab="sessions">نشست‌های فعال</button><button data-tab="activity">فعالیت ورود</button><button data-tab="ips">مدیریت IP</button><button data-tab="audit">لاگ امنیتی</button></div><div id="securityPane">در حال بارگذاری...</div></div>';
 document.body.appendChild(modal);
 const pane=modal.querySelector('#securityPane');
 const open=()=>{modal.classList.add('open');render('admins')};
 btn.onclick=open;modal.querySelector('.security-modal-close').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
 modal.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>render(b.dataset.tab));
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal)modal.classList.remove('open')});
 pane.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const id=Number(b.dataset.id),action=b.dataset.action;try{if(action==='revoke-all')await api('/api/admin/security/sessions/revoke-all',{method:'POST',body:JSON.stringify({adminId:id})});else{const body={adminId:id,action};if(action==='reset_password'){const password=prompt('رمز عبور جدید را وارد کنید (حداقل ۱۲ کاراکتر):');if(!password)return;body.password=password}const r=await api('/api/admin/security/admins/action',{method:'POST',body:JSON.stringify(body)});if(r.recoveryCodes)alert('کدهای بازیابی جدید:\n\n'+r.recoveryCodes.join('\n'))}render('admins')}catch(x){alert(x.message)}});
 return true;
}
async function render(tab){if(!modal)return;const pane=modal.querySelector('#securityPane');modal.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));pane.innerHTML='در حال بارگذاری...';try{
 if(tab==='admins'){const d=await api('/api/admin/security/admins');pane.innerHTML='<form id="newAdmin" class="security-form"><input name="fullName" placeholder="نام مدیر" required><input name="username" placeholder="نام کاربری" required><input name="email" type="email" placeholder="ایمیل" required><input name="password" type="password" placeholder="رمز عبور حداقل ۱۲ کاراکتر" required><button>ایجاد Defense Admin</button></form><table class="security-table"><thead><tr><th>حساب</th><th>وضعیت</th><th>MFA</th><th>نشست</th><th>عملیات</th></tr></thead><tbody>'+(d.admins||[]).map(a=>`<tr><td><b>${esc(a.username)}</b><br>${esc(a.full_name)}</td><td>${a.is_active?'فعال':'غیرفعال'}</td><td>${a.mfa_enabled?'فعال':'تنظیم نشده'}</td><td>${esc(a.active_sessions)}</td><td><div class="security-actions"><button data-action="${a.is_active?'disable':'enable'}" data-id="${a.id}">${a.is_active?'غیرفعال کردن':'فعال کردن'}</button><button data-action="revoke-all" data-id="${a.id}">خروج همه نشست‌ها</button><button data-action="reset_mfa" data-id="${a.id}">Reset MFA</button><button data-action="reset_recovery" data-id="${a.id}">Reset Recovery</button><button data-action="reset_password" data-id="${a.id}">تغییر رمز</button></div></td></tr>`).join('')+'</tbody></table>';pane.querySelector('#newAdmin').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/security/admins',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render('admins')}catch(x){alert(x.message)}};return}
 if(tab==='sessions'){const d=await api('/api/admin/security/sessions');pane.innerHTML=(d.sessions||[]).length?'<table class="security-table"><thead><tr><th>حساب</th><th>IP</th><th>ایجاد</th><th>انقضا</th><th>User-Agent</th><th>عملیات</th></tr></thead><tbody>'+d.sessions.map(x=>`<tr><td>${esc(x.username)}<br>${esc(x.full_name)}</td><td>${esc(x.ip_address)}</td><td>${esc(x.created_at)}</td><td>${esc(x.expires_at)}</td><td>${esc(x.user_agent)}</td><td><button data-session="${esc(x.id)}">لغو</button></td></tr>`).join('')+'</tbody></table>':'<div class="security-empty">نشست فعالی وجود ندارد.</div>';pane.querySelectorAll('[data-session]').forEach(b=>b.onclick=async()=>{try{await api('/api/admin/security/sessions/revoke',{method:'POST',body:JSON.stringify({sessionId:b.dataset.session})});render('sessions')}catch(x){alert(x.message)}});return}
 if(tab==='activity'){const d=await api('/api/admin/security/login-activity?limit=100');pane.innerHTML='<table class="security-table"><thead><tr><th>زمان</th><th>حساب</th><th>مرحله</th><th>نتیجه</th><th>IP</th><th>دلیل</th></tr></thead><tbody>'+(d.activity||[]).map(x=>`<tr><td>${esc(x.created_at)}</td><td>${esc(x.username||x.login_identifier)}</td><td>${esc(x.stage)}</td><td>${x.success?'موفق':'ناموفق'}</td><td>${esc(x.ip_address)}</td><td>${esc(x.failure_reason)}</td></tr>`).join('')+'</tbody></table>';return}
 if(tab==='ips'){const d=await api('/api/admin/security/ip-blocklist');pane.innerHTML='<form id="ipForm" class="security-form"><input name="ip" placeholder="آدرس IP" required><input name="reason" placeholder="دلیل مسدودسازی"><button>مسدود کردن IP</button></form><table class="security-table"><thead><tr><th>IP</th><th>دلیل</th><th>زمان</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>'+(d.blocks||[]).map(x=>`<tr><td>${esc(x.ip_address)}</td><td>${esc(x.reason)}</td><td>${esc(x.blocked_at)}</td><td>${x.unblocked_at?'رفع مسدودی':'مسدود'}</td><td>${x.unblocked_at?'':'<button data-unblock="'+esc(x.ip_address)+'">رفع مسدودی</button>'}</td></tr>`).join('')+'</tbody></table>';pane.querySelector('#ipForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/admin/security/ip-blocklist',{method:'POST',body:JSON.stringify({action:'block',ip:f.get('ip'),reason:f.get('reason')})});render('ips')}catch(x){alert(x.message)}};pane.querySelectorAll('[data-unblock]').forEach(b=>b.onclick=async()=>{try{await api('/api/admin/security/ip-blocklist',{method:'POST',body:JSON.stringify({action:'unblock',ip:b.dataset.unblock})});render('ips')}catch(x){alert(x.message)}});return}
 if(tab==='audit'){const d=await api('/api/admin/security/audit?limit=100');pane.innerHTML='<table class="security-table"><thead><tr><th>زمان</th><th>اجراکننده</th><th>عملیات</th><th>هدف</th><th>IP</th><th>جزئیات</th></tr></thead><tbody>'+(d.audit||[]).map(x=>`<tr><td>${esc(x.created_at)}</td><td>${esc(x.actor_username)}</td><td>${esc(x.action)}</td><td>${esc(x.target_username)}</td><td>${esc(x.ip_address)}</td><td>${esc(x.details_json)}</td></tr>`).join('')+'</tbody></table>';return}
 }catch(e){pane.innerHTML='<div class="security-note">'+esc(e.message||'خطا در دریافت اطلاعات')+'</div>'}}
function boot(){if(!init())setTimeout(boot,50)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();