(() => {
  const esc = (v) => String(v ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");
  const api = async (path, options={}) => { const r=await fetch(path,{credentials:"include",headers:{"Content-Type":"application/json"},...options}); const d=await r.json().catch(()=>({success:false,error:"پاسخ نامعتبر"})); if(!r.ok) throw new Error(d.error||"خطا"); return d; };
  const style = document.createElement("style"); style.textContent = `.security-center{margin:24px 0;padding:20px;border:1px solid #e5e7eb;border-radius:16px;background:#fff}.security-center h2{margin:0 0 16px}.security-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.security-tabs button{border:1px solid #ddd;background:#f8f8f8;border-radius:10px;padding:8px 12px;cursor:pointer}.security-tabs button.active{background:#111;color:#fff}.security-pane{overflow:auto}.security-table{width:100%;border-collapse:collapse;font-size:13px}.security-table th,.security-table td{padding:9px;border-bottom:1px solid #eee;text-align:right;vertical-align:top}.security-actions{display:flex;gap:6px;flex-wrap:wrap}.security-actions button{border:1px solid #ddd;background:#fff;border-radius:8px;padding:6px 9px;cursor:pointer}.security-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;margin-bottom:16px}.security-form input{padding:9px;border:1px solid #ddd;border-radius:8px}.security-note{padding:10px;background:#f7f7f7;border-radius:10px;margin-bottom:14px;font-size:13px}`; document.head.appendChild(style);
  document.addEventListener("DOMContentLoaded", async () => {
    const root = document.querySelector("main") || document.body; if (document.querySelector(".security-center")) return;
    const box=document.createElement("section"); box.className="security-center"; box.innerHTML='<h2>Security Center</h2><div class="security-note">مدیریت حساب‌های مدیر، Sessionها، فعالیت ورود، IP Blocklist و Audit امنیتی.</div><div class="security-tabs"><button data-tab="admins">Admin Users</button><button data-tab="sessions">Active Sessions</button><button data-tab="activity">Login Activity</button><button data-tab="ips">IP Management</button><button data-tab="audit">Audit Log</button></div><div id="securityPane" class="security-pane">در حال بارگذاری...</div>'; root.prepend(box);
    const pane=box.querySelector("#securityPane"); const buttons=[...box.querySelectorAll("[data-tab]")];
    const render = async (tab) => { buttons.forEach(b=>b.classList.toggle("active",b.dataset.tab===tab)); pane.innerHTML="در حال بارگذاری...";
      try {
        if(tab==="admins"){ const d=await api("/api/admin/security/admins"); pane.innerHTML='<form id="newAdmin" class="security-form"><input name="fullName" placeholder="نام مدیر" required><input name="username" placeholder="نام کاربری" required><input name="email" type="email" placeholder="ایمیل اختیاری"><input name="password" type="password" placeholder="رمز عبور حداقل ۱۲ کاراکتر" required><button type="submit">ایجاد Defense Admin</button></form><table class="security-table"><thead><tr><th>Username</th><th>Status</th><th>MFA</th><th>Sessions</th><th>Actions</th></tr></thead><tbody>'+d.admins.map(a=>`<tr><td><strong>${esc(a.username)}</strong><br>${esc(a.full_name)}</td><td>${a.is_active?'فعال':'غیرفعال'}</td><td>${a.mfa_enabled?'فعال':'تنظیم نشده'}</td><td>${esc(a.active_sessions)}</td><td><div class="security-actions"><button data-action="${a.is_active?'disable':'enable'}" data-id="${a.id}">${a.is_active?'Disable':'Enable'}</button><button data-action="revoke-all" data-id="${a.id}">Revoke Sessions</button><button data-action="reset-mfa" data-id="${a.id}">Reset MFA</button><button data-action="reset-recovery" data-id="${a.id}">Reset Recovery</button></div></td></tr>`).join('')+'</tbody></table>';
          pane.querySelector("#newAdmin").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/admin/security/admins',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});alert('Admin ایجاد شد. برای MFA، مدیر جدید باید اولین ورود خود را انجام دهد.');render('admins')}catch(x){alert(x.message)}};
        }
        if(tab==="sessions"){ const d=await api('/api/admin/security/sessions'); pane.innerHTML='<table class="security-table"><thead><tr><th>Account</th><th>IP</th><th>Created</th><th>Expires</th><th>User-Agent</th><th>Action</th></tr></thead><tbody>'+d.sessions.map(s=>`<tr><td>${esc(s.username)}<br>${esc(s.full_name)}</td><td>${esc(s.ip_address)}</td><td>${esc(s.created_at)}</td><td>${esc(s.expires_at)}</td><td>${esc(s.user_agent)}</td><td><button data-session="${esc(s.id)}">Revoke</button></td></tr>`).join('')+'</tbody></table>'; pane.querySelectorAll('[data-session]').forEach(b=>b.onclick=async()=>{await api('/api/admin/security/sessions/revoke',{method:'POST',body:JSON.stringify({sessionId:b.dataset.session})});render('sessions')}); }
        if(tab==="activity"){ const d=await api('/api/admin/security/login-activity?limit=100'); pane.innerHTML='<table class="security-table"><thead><tr><th>Time</th><th>Account</th><th>Stage</th><th>Result</th><th>IP</th><th>Reason</th></tr></thead><tbody>'+d.activity.map(x=>`<tr><td>${esc(x.created_at)}</td><td>${esc(x.username||x.login_identifier)}</td><td>${esc(x.stage)}</td><td>${x.success?'Success':'Failed'}</td><td>${esc(x.ip_address)}</td><td>${esc(x.failure_reason)}</td></tr>`).join('')+'</tbody></table>'; }
        if(tab==="ips"){ const d=await api('/api/admin/security/ip-blocklist'); pane.innerHTML='<form id="ipForm" class="security-form"><input name="ip" placeholder="IP address" required><input name="reason" placeholder="دلیل Block"><button type="submit">Block IP</button></form><table class="security-table"><thead><tr><th>IP</th><th>Reason</th><th>Blocked At</th><th>Status</th><th>Action</th></tr></thead><tbody>'+d.blocks.map(x=>`<tr><td>${esc(x.ip_address)}</td><td>${esc(x.reason)}</td><td>${esc(x.blocked_at)}</td><td>${x.unblocked_at?'Unblocked':'Blocked'}</td><td>${x.unblocked_at?'':'<button data-unblock="'+esc(x.ip_address)+'">Unblock</button>'}</td></tr>`).join('')+'</tbody></table>'; pane.querySelector('#ipForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api('/api/admin/security/ip-blocklist',{method:'POST',body:JSON.stringify({action:'block',ip:f.get('ip'),reason:f.get('reason')})});render('ips')}; pane.querySelectorAll('[data-unblock]').forEach(b=>b.onclick=async()=>{await api('/api/admin/security/ip-blocklist',{method:'POST',body:JSON.stringify({action:'unblock',ip:b.dataset.unblock})});render('ips')}); }
        if(tab==="audit"){ const d=await api('/api/admin/security/audit?limit=100'); pane.innerHTML='<table class="security-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>IP</th><th>Details</th></tr></thead><tbody>'+d.audit.map(x=>`<tr><td>${esc(x.created_at)}</td><td>${esc(x.actor_username)}</td><td>${esc(x.action)}</td><td>${esc(x.target_username)}</td><td>${esc(x.ip_address)}</td><td>${esc(x.details_json)}</td></tr>`).join('')+'</tbody></table>'; }
      } catch(e){ pane.innerHTML='<div class="security-note">'+esc(e.message||'خطا در دریافت اطلاعات')+'</div>'; }
    };
    buttons.forEach(b=>b.onclick=()=>render(b.dataset.tab)); render('admins');
    pane.addEventListener('click', async e=>{const b=e.target.closest('[data-action]'); if(!b)return; const id=Number(b.dataset.id), action=b.dataset.action; try{if(action==='revoke-all')await api('/api/admin/security/sessions/revoke-all',{method:'POST',body:JSON.stringify({adminId:id})});else await api('/api/admin/security/admins/action',{method:'POST',body:JSON.stringify({adminId:id,action})});render('admins')}catch(x){alert(x.message)}});
  });
})();
